In [1]:
import numpy as np
marks = np.arange(20)
print(marks)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
import numpy as np
zero = np.zeros(6)  #when need zero
print(zero)
one = np.ones(7)
print(one)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


In [5]:
import numpy as np
arr = [20,15,25,30,35,40,50]
mean = np.mean(arr)
median=np.median(arr)
standard_deviation = np.std(arr)
print(mean)
print(median)
print(standard_deviation)

30.714285714285715
30.0
11.157499537009505


In [8]:
import numpy as np
a = np.arange(0,5,2)
print(a)

[0 2 4]


In [9]:
print(np.__version__)

2.1.3


In [10]:
#to get ans in integer
import numpy as np
zero = np.zeros(6,dtype= "int")
print (zero)


[0 0 0 0 0 0]


In [11]:
#to get in matrix form(rows,coulmns)
zar = np.zeros((4,5))
print(zar)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#covering list to array 

A= [1,23,45,67,78]
Aa= np.array(1)
print(l)

[1, 23, 45, 67, 78]


In [2]:
import numpy as np
zar = np.zeros((4,5),dtype = "int")
print(zar)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
1. Array Creation

np.array() – create array from list/tuple

np.zeros(shape) – array of zeros

np.ones(shape) – array of ones

np.full(shape, value) – fill with a given value

np.arange(start, stop, step) – like Python range

np.linspace(start, stop, num) – evenly spaced numbers

np.eye(n) – identity matrix

np.random.randint(low, high, size) – random integers

np.random.rand(size) – random floats [0,1)

np.random.randn(size) – random numbers from normal distribution

In [5]:
  #array creation
import numpy as np
arr = np.arange(2,6,3) #np.arange(start,stop,step)

print (arr)

[2 5]


In [6]:
import numpy as np
arr = np.arange(5,7)
print(arr)

[5 6]


In [7]:
import numpy as np
arr = np.full(4,7)    #np.full(shape,value) This function creates an array of a given shape (rows × cols) and fills it with a specific value.
print(arr)

[7 7 7 7]


In [9]:
#line space returns evenly spaced numbers between start and end
#arr=np.linspace(start, stop, num)
import numpy as np
arr = np.linspace(2,10,3)
print(arr)

[ 2.  6. 10.]


In [16]:
import numpy as np
arr= np.random.randint(2,10,5) #1D array of 5 numbers
print(arr)

[8 6 4 7 4]


In [14]:
#2Darray of randon numbers
import numpy as np
matrix =np.random.randint(5,50,size=(3,4)) #size=(rows,columns)
print(matrix)

[[ 9 11 40  9]
 [42 11 42  5]
 [43 25  8 22]]


In [15]:
#dice simulation
import numpy as np
dice = np.random.randint(1,7,10)
print(dice)

[4 5 6 2 4 3 2 1 4 1]


In [17]:
#identity matrix 
import numpy as np
arr = np.eye(4) #(4 by 4 identity matrix)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
import numpy as np
arr = np.random.rand(5) #random floats [0,1) jtna size utni values
print(arr)

[0.8493206  0.75301852 0.39301296 0.70361477 0.95196121]


In [19]:
import numpy as np
arr = np.random.randn(6)
print(arr)

[ 1.16262574 -0.12603318  0.16349549 -0.27838685 -1.52455617 -0.51727393]


In [ ]:
Key Difference from rand and randint
np.random.rand() → uniform distribution [0,1)

np.random.randint() → random integers in range

np.random.randn() → normal distribution (bell curve), mean=0, std=1

In [ ]:
2. Array Inspection
arr.shape – dimensions (rows, cols)

arr.ndim – number of dimensions

arr.size – total elements

arr.dtype – data type

arr.itemsize – size of one element in bytes

In [1]:
import numpy as np
matrix = np.array([[2,3,4],[5,6,7]])
print(matrix)




[[2 3 4]
 [5 6 7]]


In [4]:
import numpy as np
Mat= np.shape([[1,2,3,],[3,4,5]])
print(Mat)

(2, 3)


In [6]:
import numpy as np
mat = np.ndim([[[1,2,3],[3,4,5],[5,6,7]]])
print(mat)

3


In [9]:
import numpy as np
mat = np.size([[[1,2,3],[3,4,5],[5,6,7]]])
print(mat)

9


In [ ]:
3. Indexing & Slicing

arr[2], arr[1:4], arr[:, 0] – slicing like lists

arr.flatten() – convert 2D to 1D

arr.reshape(rows, cols) – reshape array

arr.T – transpose matrix

In [13]:
import numpy as np
mat = ([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(mat)

[[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]


In [16]:
import numpy as np
mat = ([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
mat = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print("original array:\n",mat)

original array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [15]:
#slicing
import numpy as np
mat = ([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
mat3d = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(mat3d[2,3])
print(mat3d[1,3])
print(mat3d[:,0]) #frst col

print(mat3d[:,1]) #2nd col
print(mat3d[1,:]) #Now, mat3d[1, :]1 → choose layer 1 (the 2nd layer).: → take all rows from that layer.

120
80
[10 50 90]
[ 20  60 100]
[50 60 70 80]


In [2]:
#flatten

mat = ([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
mat = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
flat = mat.flatten()
print(flat)

[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [27]:
#reshape
import numpy as np
mat = ([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]   #3*4=12
])
mat = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
reshaped = mat.reshape(4,3) # it can be reshaped only if total elts before and after reshape is same 4*3=12
print(reshaped)


[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [29]:
import numpy as np
mat = ([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]   
])
mat = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]   
])

transposed = mat.T
print(transposed)

[[ 10  50  90]
 [ 20  60 100]
 [ 30  70 110]
 [ 40  80 120]]


In [ ]:
🔹 4. Mathematical Operations

np.add(arr1, arr2) / arr1 + arr2

np.subtract(arr1, arr2) / arr1 - arr2

np.multiply(arr1, arr2) / arr1 * arr2

np.divide(arr1, arr2) / arr1 / arr2

np.power(arr, 2) / arr**2

np.sqrt(arr) – square root

np.exp(arr) – exponent

np.log(arr) – natural log

np.abs(arr) – absolute values

In [30]:
import numpy as np
arr1 = ([1,2,3])
arr2 = ([3,4,5])
sum = np.add(arr1,arr2)
diff = np.subtract(arr1,arr2)
mul = np.multiply(arr1,arr2)
div = np.divide(arr1,arr2)
print(sum)
print(diff)
print(mul)
print(div)



[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]


In [34]:
import numpy as np
arr1 = ([1,2,3])
power = np.power(arr1,2)
sqroot = np.sqrt([4,9,16])
print(power)
print(sqroot)

[1 4 9]
[2. 3. 4.]


In [39]:
import numpy as np
arr = np.array([4,9,16])
result = np.sqrt(arr)
result_int = result.astype(int)
arr = np.exp(arr)
print(arr)
print(result_int)

[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[2 3 4]


In [40]:
import numpy as np
arr = np.array([-1,2,-3,-4,-5])
arr = np.abs(arr)
print(arr)

[1 2 3 4 5]


In [ ]:
🔹 5. Statistical Functions

np.min(arr) – minimum

np.max(arr) – maximum

np.mean(arr) – mean

np.median(arr) – median

np.std(arr) – standard deviation

np.var(arr) – variance

np.percentile(arr, q) – percentile

np.sum(arr) – sum of elements

np.cumsum(arr) – cumulative sum


In [41]:
import numpy as np
arr = [2,3,4,5,6,7]
arr = np.array([2,3,4,5,6,7])
arr_m1 = np.min(arr)
arr_m2 = np.max(arr)
arr_m3 = np.mean(arr)
arr_m4 = np.median(arr)
arr_m5 = np.std(arr)
print(arr_m1)
print(arr_m2)
print(arr_m3)
print(arr_m4)
print(arr_m5)



2
7
4.5
4.5
1.707825127659933


In [42]:
import numpy as np
a2 = [2,3,4,5,6,7]
a2 = np.array([2,3,4,5,6,7])
a3 = np.var(a2)
a4 = np.sum(a2)
a5 = np.cumsum(a2)
print(a3)
print(a4)
print(a5)


2.9166666666666665
27
[ 2  5  9 14 20 27]


In [ ]:
🔹 6. Conditional & Boolean

np.where(condition, x, y) – conditional selection

np.any(arr > value) – check if any element matches

np.all(arr > value) – check if all match

np.unique(arr) – unique elements

np.in1d(arr1, arr2) – check membership

In [5]:
arr = [20,35,40,45,50,60]
result = np.where( arr>35 ,"yes","no")
print(result)

['no' 'no' 'yes' 'yes' 'yes' 'yes']


In [ ]:
🔹 Common NumPy String Methods (np.char)

Here are the most useful ones:

np.char.add() → Concatenate strings

np.char.multiply() → Repeat strings

np.char.lower() → Convert to lowercase

np.char.upper() → Convert to uppercase

np.char.title() → Capitalize each word

np.char.capitalize() → Capitalize first letter

np.char.strip() → Remove leading/trailing spaces (or characters)

np.char.split() → Split string into list

np.char.join() → Join characters with a separator

np.char.replace() → Replace substrings

np.char.equal() → Element-wise string comparison

np.char.count() → Count occurrences of substring

np.char.find() → Find position of substring

In [16]:
arr = [[[1,2,3],[3,4,5],[6,7,8]]]
arr = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
fla = arr.flatten()
print(fla)

[1 2 3 3 4 5 6 7 8]


In [22]:
arr = np.array([[2,4,5,6,7],
                [4,5,6,7,9],
                [7,8,9,10,11]])
re = arr.reshape(5,3)
print(re)

[[ 2  4  5]
 [ 6  7  4]
 [ 5  6  7]
 [ 9  7  8]
 [ 9 10 11]]


In [24]:
arr = np.array([[2,4,5,6,7],
                [4,5,6,7,9],
                [7,8,9,10,11]])
re = arr.reshape(3,1,5) # (no  of matrices required,rows,columns)
print(re)

[[[ 2  4  5  6  7]]

 [[ 4  5  6  7  9]]

 [[ 7  8  9 10 11]]]


In [4]:
import numpy as np
arr = np.array([2,3,4,5,6,7,8,9,10,22,34,56,56,67])
ar1 = arr.reshape(7,2,1)
print(ar1)

[[[ 2]
  [ 3]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 9]]

 [[10]
  [22]]

 [[34]
  [56]]

 [[56]
  [67]]]


In [8]:
import numpy as np
arr = np.array([[2,3,4,5],[3,4,5,6],[4,5,6,7]])
fla = arr.reshape(3,2,2)
print(fla)

[[[2 3]
  [4 5]]

 [[3 4]
  [5 6]]

 [[4 5]
  [6 7]]]


In [3]:
arr = ["Numpy", "is" , "The" , "Library" , "of" , "Python"]
arr = np.array(["Numpy", "is" , "The" , "Library" , "of" , "Python"])
arr1 = np.char.add(arr , "")
a1 = np.char.add(arr , "!!")
print(a1)
print(arr1)

['Numpy!!' 'is!!' 'The!!' 'Library!!' 'of!!' 'Python!!']
['Numpy' 'is' 'The' 'Library' 'of' 'Python']


In [7]:
arr = ["Numpy", "is" , "The" , "Library" , "of" , "Python"]
arr = np.array(["Numpy", "is" , "The" , "Library" , "of" , "Python"])
arr1 = np.char.lower(arr)
print(np.char.upper(arr))
print(arr1)

['NUMPY' 'IS' 'THE' 'LIBRARY' 'OF' 'PYTHON']
['numpy' 'is' 'the' 'library' 'of' 'python']


In [2]:
import numpy as np
print(np.char.multiply("ha" ,6 ))

hahahahahaha


In [9]:
print(np.char.title("welcome to the world of technology"))

Welcome To The World Of Technology


In [13]:
arr = ["Numpy", "is" , "The" , "Library" , "of" , "Python"]
print(np.char.capitalize("Welcome To The World Of Technology"))
print (np.char.split(arr , sep =","))

Welcome to the world of technology
[list(['Numpy']) list(['is']) list(['The']) list(['Library']) list(['of'])
 list(['Python'])]


In [16]:
arr = ["Numpy", "is" , "The" , "Library" , "of" , "Python"]
arr1 = np.array(["Numpy", "is" , "The" , "Library" , "of" , "Python"])
arr2 = np.char.split(arr1,",")
print(arr2)

[list(['Numpy']) list(['is']) list(['The']) list(['Library']) list(['of'])
 list(['Python'])]


In [1]:
n = int(input("enter a number:"))
for i in range(1,11):
    print(n ,"*",i,"=",n*i)

enter a number: 23


23 * 1 = 23
23 * 2 = 46
23 * 3 = 69
23 * 4 = 92
23 * 5 = 115
23 * 6 = 138
23 * 7 = 161
23 * 8 = 184
23 * 9 = 207
23 * 10 = 230


In [4]:
import pandas as pd
data = {
    "Nmae" :["aisha","romaisa","javeria"],
    "Age":[25,30,32] ,
    "city":["Lahore","gujranwala","Islamabad"]
}
df = pd.DataFrame(data)
print(df)

      Nmae  Age        city
0    aisha   25      Lahore
1  romaisa   30  gujranwala
2  javeria   32   Islamabad
